version: '3'
services:
  flux-capacitor:
    image: fluxcapacitorio/flux-capacitor-test:0.334
    ports:
      - "5200:5005" #debugging

  web:
    depends_on:
      - flux-capacitor
    build:
      context: ./web/.
    image: downspin-sample-web:tag
    environment:
      - MESSAGING_ENDPOINT=ws://flux-capacitor:8888
    ports:
      - "8090:8080"
      - "5100:5005" #debugging

  app:
    depends_on:
      - flux-capacitor
    build:
      context: ./app/.
    image: downspin-sample-app:tag
    environment:
      - MESSAGING_ENDPOINT=ws://flux-capacitor:8888

volumes:
  config:
    driver: local
  flux-capacitor:
    driver: local
